slice_name: ALL spendings by month
description: null
certified_by: null
certification_details: null
viz_type: mixed_timeseries
params:
  datasource: 57__table
  viz_type: mixed_timeseries
  slice_id: 263
  x_axis: datetime
  time_grain_sqla: P1M
  metrics:
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: ammount
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 2276
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: REAL
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: SUM(ammount)
    optionName: metric_442bc2t8tqt_in75geh6bn
    sqlExpression: null
  groupby:
  - category_fancy
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_gkxdyhx14m_1501t0fskxc
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: datetime
  - clause: WHERE
    comparator: '0'
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_1bj8l5qm22o_fkjtpmak10k
    isExtra: false
    isNew: false
    operator: <
    operatorId: LESS_THAN
    sqlExpression: null
    subject: ammount
  - clause: WHERE
    comparator:
    - "\u041F\u0435\u0440\u0435\u0432\u043E\u0434 \u043C\u0435\u0436\u0434\u0443 \u0441\
      \u0447\u0435\u0442\u0430\u043C\u0438"
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_1i6pkjjtvaf_a6n87w47lgw
    isExtra: false
    isNew: false
    operator: NOT IN
    operatorId: NOT_IN
    sqlExpression: null
    subject: description
  - clause: WHERE
    comparator:
    - "\u041F\u0435\u0440\u0435\u0432\u043E\u0434 \u043C\u0435\u0436\u0434\u0443 \u0441\
      \u0447\u0435\u0442\u0430\u043C\u0438"
    - transaction
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_c6gzyhiu6i_dskykg5twuc
    isExtra: false
    isNew: false
    operator: NOT IN
    operatorId: NOT_IN
    sqlExpression: null
    subject: category
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  comparison_type: values
  metrics_b:
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: ammount
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 2276
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: REAL
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: SUM(ammount)
    optionName: metric_kz64rhdr6b8_u7entrll8eg
    sqlExpression: null
  groupby_b: []
  adhoc_filters_b:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_dqxozy0iy8w_7t3q2xcj56o
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: datetime
  - clause: WHERE
    comparator: '0'
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_dph3wd5ghtj_y98vx5mjqx
    isExtra: false
    isNew: false
    operator: <
    operatorId: LESS_THAN
    sqlExpression: null
    subject: ammount
  - clause: WHERE
    comparator:
    - "\u041F\u0435\u0440\u0435\u0432\u043E\u0434 \u043C\u0435\u0436\u0434\u0443 \u0441\
      \u0447\u0435\u0442\u0430\u043C\u0438"
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_w541ofi4lh_0n5cxxpwyqn
    isExtra: false
    isNew: false
    operator: NOT IN
    operatorId: NOT_IN
    sqlExpression: null
    subject: description
  - clause: WHERE
    comparator:
    - transaction
    - "\u041F\u0435\u0440\u0435\u0432\u043E\u0434 \u043C\u0435\u0436\u0434\u0443 \u0441\
      \u0447\u0435\u0442\u0430\u043C\u0438"
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_lsg88yu7bla_1tctpixdu62
    isExtra: false
    isNew: false
    operator: NOT IN
    operatorId: NOT_IN
    sqlExpression: null
    subject: category
  order_desc_b: true
  row_limit_b: 10000
  truncate_metric_b: true
  rolling_type_b: mean
  rolling_periods_b: 12
  min_periods_b: 1
  comparison_type_b: values
  annotation_layers: []
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  color_scheme: supersetColors
  seriesType: bar
  stack: true
  opacity: 0.2
  markerSize: 6
  seriesTypeB: smooth
  areaB: false
  show_valueB: true
  opacityB: 0.3
  markerEnabledB: true
  markerSizeB: 9
  zoomable: true
  minorTicks: false
  show_legend: true
  legendType: scroll
  legendOrientation: top
  legendMargin: ''
  x_axis_time_format: smart_date
  rich_tooltip: true
  showTooltipTotal: true
  showTooltipPercentage: true
  tooltipTimeFormat: smart_date
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  y_axis_bounds_secondary:
  - null
  - null
  y_axis_format_secondary: SMART_NUMBER
  extra_form_data: {}
  dashboards:
  - 24
query_context: "{\"datasource\":{\"id\":57,\"type\":\"table\"},\"force\":false,\"\
  queries\":[{\"filters\":[{\"col\":\"datetime\",\"op\":\"TEMPORAL_RANGE\",\"val\"\
  :\"No filter\"},{\"col\":\"ammount\",\"op\":\"<\",\"val\":\"0\"},{\"col\":\"description\"\
  ,\"op\":\"NOT IN\",\"val\":[\"\u041F\u0435\u0440\u0435\u0432\u043E\u0434 \u043C\u0435\
  \u0436\u0434\u0443 \u0441\u0447\u0435\u0442\u0430\u043C\u0438\"]},{\"col\":\"category\"\
  ,\"op\":\"NOT IN\",\"val\":[\"\u041F\u0435\u0440\u0435\u0432\u043E\u0434 \u043C\u0435\
  \u0436\u0434\u0443 \u0441\u0447\u0435\u0442\u0430\u043C\u0438\",\"transaction\"\
  ]}],\"extras\":{\"time_grain_sqla\":\"P1M\",\"having\":\"\",\"where\":\"\"},\"applied_time_extras\"\
  :{},\"columns\":[{\"timeGrain\":\"P1M\",\"columnType\":\"BASE_AXIS\",\"sqlExpression\"\
  :\"datetime\",\"label\":\"datetime\",\"expressionType\":\"SQL\"},\"category_fancy\"\
  ],\"metrics\":[{\"aggregate\":\"SUM\",\"column\":{\"advanced_data_type\":null,\"\
  certification_details\":null,\"certified_by\":null,\"column_name\":\"ammount\",\"\
  description\":null,\"expression\":null,\"filterable\":true,\"groupby\":true,\"id\"\
  :2276,\"is_certified\":false,\"is_dttm\":false,\"python_date_format\":null,\"type\"\
  :\"REAL\",\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\":null},\"\
  datasourceWarning\":false,\"expressionType\":\"SIMPLE\",\"hasCustomLabel\":false,\"\
  label\":\"SUM(ammount)\",\"optionName\":\"metric_442bc2t8tqt_in75geh6bn\",\"sqlExpression\"\
  :null}],\"annotation_layers\":[],\"row_limit\":10000,\"series_columns\":[\"category_fancy\"\
  ],\"series_limit\":0,\"url_params\":{},\"custom_params\":{},\"custom_form_data\"\
  :{},\"time_offsets\":[],\"post_processing\":[{\"operation\":\"pivot\",\"options\"\
  :{\"index\":[\"datetime\"],\"columns\":[\"category_fancy\"],\"aggregates\":{\"SUM(ammount)\"\
  :{\"operator\":\"mean\"}},\"drop_missing_columns\":true}},{\"operation\":\"rename\"\
  ,\"options\":{\"columns\":{\"SUM(ammount)\":null},\"level\":0,\"inplace\":true}},{\"\
  operation\":\"flatten\"}],\"orderby\":[[{\"aggregate\":\"SUM\",\"column\":{\"advanced_data_type\"\
  :null,\"certification_details\":null,\"certified_by\":null,\"column_name\":\"ammount\"\
  ,\"description\":null,\"expression\":null,\"filterable\":true,\"groupby\":true,\"\
  id\":2276,\"is_certified\":false,\"is_dttm\":false,\"python_date_format\":null,\"\
  type\":\"REAL\",\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\":null},\"\
  datasourceWarning\":false,\"expressionType\":\"SIMPLE\",\"hasCustomLabel\":false,\"\
  label\":\"SUM(ammount)\",\"optionName\":\"metric_442bc2t8tqt_in75geh6bn\",\"sqlExpression\"\
  :null},false]]},{\"filters\":[{\"col\":\"datetime\",\"op\":\"TEMPORAL_RANGE\",\"\
  val\":\"No filter\"},{\"col\":\"ammount\",\"op\":\"<\",\"val\":\"0\"},{\"col\":\"\
  description\",\"op\":\"NOT IN\",\"val\":[\"\u041F\u0435\u0440\u0435\u0432\u043E\u0434\
  \ \u043C\u0435\u0436\u0434\u0443 \u0441\u0447\u0435\u0442\u0430\u043C\u0438\"]},{\"\
  col\":\"category\",\"op\":\"NOT IN\",\"val\":[\"transaction\",\"\u041F\u0435\u0440\
  \u0435\u0432\u043E\u0434 \u043C\u0435\u0436\u0434\u0443 \u0441\u0447\u0435\u0442\
  \u0430\u043C\u0438\"]}],\"extras\":{\"time_grain_sqla\":\"P1M\",\"having\":\"\"\
  ,\"where\":\"\"},\"applied_time_extras\":{},\"columns\":[{\"timeGrain\":\"P1M\"\
  ,\"columnType\":\"BASE_AXIS\",\"sqlExpression\":\"datetime\",\"label\":\"datetime\"\
  ,\"expressionType\":\"SQL\"}],\"metrics\":[{\"aggregate\":\"SUM\",\"column\":{\"\
  advanced_data_type\":null,\"certification_details\":null,\"certified_by\":null,\"\
  column_name\":\"ammount\",\"description\":null,\"expression\":null,\"filterable\"\
  :true,\"groupby\":true,\"id\":2276,\"is_certified\":false,\"is_dttm\":false,\"python_date_format\"\
  :null,\"type\":\"REAL\",\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\"\
  :null},\"datasourceWarning\":false,\"expressionType\":\"SIMPLE\",\"hasCustomLabel\"\
  :false,\"label\":\"SUM(ammount)\",\"optionName\":\"metric_kz64rhdr6b8_u7entrll8eg\"\
  ,\"sqlExpression\":null}],\"annotation_layers\":[],\"row_limit\":10000,\"series_columns\"\
  :[],\"series_limit\":0,\"url_params\":{},\"custom_params\":{},\"custom_form_data\"\
  :{},\"time_offsets\":[],\"post_processing\":[{\"operation\":\"pivot\",\"options\"\
  :{\"index\":[\"datetime\"],\"columns\":[],\"aggregates\":{\"SUM(ammount)\":{\"operator\"\
  :\"mean\"}},\"drop_missing_columns\":true}},{\"operation\":\"rolling\",\"options\"\
  :{\"rolling_type\":\"mean\",\"window\":12,\"min_periods\":1,\"columns\":{\"SUM(ammount)\"\
  :\"SUM(ammount)\"}}},{\"operation\":\"flatten\"}],\"orderby\":[[{\"aggregate\":\"\
  SUM\",\"column\":{\"advanced_data_type\":null,\"certification_details\":null,\"\
  certified_by\":null,\"column_name\":\"ammount\",\"description\":null,\"expression\"\
  :null,\"filterable\":true,\"groupby\":true,\"id\":2276,\"is_certified\":false,\"\
  is_dttm\":false,\"python_date_format\":null,\"type\":\"REAL\",\"type_generic\":0,\"\
  verbose_name\":null,\"warning_markdown\":null},\"datasourceWarning\":false,\"expressionType\"\
  :\"SIMPLE\",\"hasCustomLabel\":false,\"label\":\"SUM(ammount)\",\"optionName\":\"\
  metric_kz64rhdr6b8_u7entrll8eg\",\"sqlExpression\":null},false]]}],\"form_data\"\
  :{\"datasource\":\"57__table\",\"viz_type\":\"mixed_timeseries\",\"slice_id\":263,\"\
  x_axis\":\"datetime\",\"time_grain_sqla\":\"P1M\",\"metrics\":[{\"aggregate\":\"\
  SUM\",\"column\":{\"advanced_data_type\":null,\"certification_details\":null,\"\
  certified_by\":null,\"column_name\":\"ammount\",\"description\":null,\"expression\"\
  :null,\"filterable\":true,\"groupby\":true,\"id\":2276,\"is_certified\":false,\"\
  is_dttm\":false,\"python_date_format\":null,\"type\":\"REAL\",\"type_generic\":0,\"\
  verbose_name\":null,\"warning_markdown\":null},\"datasourceWarning\":false,\"expressionType\"\
  :\"SIMPLE\",\"hasCustomLabel\":false,\"label\":\"SUM(ammount)\",\"optionName\":\"\
  metric_442bc2t8tqt_in75geh6bn\",\"sqlExpression\":null}],\"groupby\":[\"category_fancy\"\
  ],\"adhoc_filters\":[{\"clause\":\"WHERE\",\"comparator\":\"No filter\",\"datasourceWarning\"\
  :false,\"expressionType\":\"SIMPLE\",\"filterOptionName\":\"filter_gkxdyhx14m_1501t0fskxc\"\
  ,\"isExtra\":false,\"isNew\":false,\"operator\":\"TEMPORAL_RANGE\",\"sqlExpression\"\
  :null,\"subject\":\"datetime\"},{\"clause\":\"WHERE\",\"comparator\":\"0\",\"datasourceWarning\"\
  :false,\"expressionType\":\"SIMPLE\",\"filterOptionName\":\"filter_1bj8l5qm22o_fkjtpmak10k\"\
  ,\"isExtra\":false,\"isNew\":false,\"operator\":\"<\",\"operatorId\":\"LESS_THAN\"\
  ,\"sqlExpression\":null,\"subject\":\"ammount\"},{\"clause\":\"WHERE\",\"comparator\"\
  :[\"\u041F\u0435\u0440\u0435\u0432\u043E\u0434 \u043C\u0435\u0436\u0434\u0443 \u0441\
  \u0447\u0435\u0442\u0430\u043C\u0438\"],\"datasourceWarning\":false,\"expressionType\"\
  :\"SIMPLE\",\"filterOptionName\":\"filter_1i6pkjjtvaf_a6n87w47lgw\",\"isExtra\"\
  :false,\"isNew\":false,\"operator\":\"NOT IN\",\"operatorId\":\"NOT_IN\",\"sqlExpression\"\
  :null,\"subject\":\"description\"},{\"clause\":\"WHERE\",\"comparator\":[\"\u041F\
  \u0435\u0440\u0435\u0432\u043E\u0434 \u043C\u0435\u0436\u0434\u0443 \u0441\u0447\
  \u0435\u0442\u0430\u043C\u0438\",\"transaction\"],\"datasourceWarning\":false,\"\
  expressionType\":\"SIMPLE\",\"filterOptionName\":\"filter_c6gzyhiu6i_dskykg5twuc\"\
  ,\"isExtra\":false,\"isNew\":false,\"operator\":\"NOT IN\",\"operatorId\":\"NOT_IN\"\
  ,\"sqlExpression\":null,\"subject\":\"category\"}],\"order_desc\":true,\"row_limit\"\
  :10000,\"truncate_metric\":true,\"comparison_type\":\"values\",\"annotation_layers\"\
  :[],\"x_axis_title_margin\":15,\"y_axis_title_margin\":15,\"y_axis_title_position\"\
  :\"Left\",\"color_scheme\":\"supersetColors\",\"seriesType\":\"bar\",\"stack\":true,\"\
  opacity\":0.2,\"markerSize\":6,\"seriesTypeB\":\"smooth\",\"areaB\":false,\"show_valueB\"\
  :true,\"opacityB\":0.3,\"markerEnabledB\":true,\"markerSizeB\":9,\"zoomable\":true,\"\
  minorTicks\":false,\"show_legend\":true,\"legendType\":\"scroll\",\"legendOrientation\"\
  :\"top\",\"legendMargin\":\"\",\"x_axis_time_format\":\"smart_date\",\"rich_tooltip\"\
  :true,\"showTooltipTotal\":true,\"showTooltipPercentage\":true,\"tooltipTimeFormat\"\
  :\"smart_date\",\"truncateXAxis\":true,\"y_axis_bounds\":[null,null],\"y_axis_format\"\
  :\"SMART_NUMBER\",\"y_axis_bounds_secondary\":[null,null],\"y_axis_format_secondary\"\
  :\"SMART_NUMBER\",\"extra_form_data\":{},\"dashboards\":[24],\"force\":false,\"\
  result_format\":\"json\",\"result_type\":\"full\"},\"result_format\":\"json\",\"\
  result_type\":\"full\"}"
cache_timeout: null
uuid: 2276d3d8-e172-4185-b941-5a11c629819b
version: 1.0.0
dataset_uuid: 6f0e873c-4069-47a3-9142-59597901384a
