slice_name: BarsByCards
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 57__table
  viz_type: echarts_timeseries_bar
  x_axis: datetime
  time_grain_sqla: P1M
  metrics:
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: ammount
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 2276
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: REAL
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: SUM(ammount)
    optionName: metric_j04h4z2jwd_5xpcnrl545
  groupby:
  - card_name
  adhoc_filters:
  - expressionType: SIMPLE
    subject: datetime
    operator: TEMPORAL_RANGE
    comparator: No filter
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_agah3g432sq_8qat3cvmn7f
  - expressionType: SIMPLE
    subject: ammount
    operator: <
    operatorId: LESS_THAN
    comparator: '0'
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_a7f2cb6hbci_4ncy1r8ppk7
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: vertical
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  show_value: false
  stack: Stack
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  rich_tooltip: true
  showTooltipTotal: true
  showTooltipPercentage: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 24
query_context: '{"datasource":{"id":57,"type":"table"},"force":false,"queries":[{"filters":[{"col":"datetime","op":"TEMPORAL_RANGE","val":"No
  filter"},{"col":"ammount","op":"<","val":"0"}],"extras":{"time_grain_sqla":"P1M","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1M","columnType":"BASE_AXIS","sqlExpression":"datetime","label":"datetime","expressionType":"SQL"},"card_name"],"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"ammount","description":null,"expression":null,"filterable":true,"groupby":true,"id":2276,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"REAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(ammount)","optionName":"metric_j04h4z2jwd_5xpcnrl545"}],"orderby":[[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"ammount","description":null,"expression":null,"filterable":true,"groupby":true,"id":2276,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"REAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(ammount)","optionName":"metric_j04h4z2jwd_5xpcnrl545"},false]],"annotation_layers":[],"row_limit":10000,"series_columns":["card_name"],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["datetime"],"columns":["card_name"],"aggregates":{"SUM(ammount)":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"rename","options":{"columns":{"SUM(ammount)":null},"level":0,"inplace":true}},{"operation":"flatten"}]}],"form_data":{"datasource":"57__table","viz_type":"echarts_timeseries_bar","x_axis":"datetime","time_grain_sqla":"P1M","metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"ammount","description":null,"expression":null,"filterable":true,"groupby":true,"id":2276,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"REAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(ammount)","optionName":"metric_j04h4z2jwd_5xpcnrl545"}],"groupby":["card_name"],"adhoc_filters":[{"expressionType":"SIMPLE","subject":"datetime","operator":"TEMPORAL_RANGE","comparator":"No
  filter","clause":"WHERE","sqlExpression":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_agah3g432sq_8qat3cvmn7f"},{"expressionType":"SIMPLE","subject":"ammount","operator":"<","operatorId":"LESS_THAN","comparator":"0","clause":"WHERE","sqlExpression":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_a7f2cb6hbci_4ncy1r8ppk7"}],"row_limit":10000,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"orientation":"vertical","x_axis_title_margin":15,"y_axis_title_margin":15,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetColors","show_value":false,"stack":"Stack","show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","y_axis_format":"SMART_NUMBER","truncateXAxis":true,"y_axis_bounds":[null,null],"rich_tooltip":true,"showTooltipTotal":true,"showTooltipPercentage":true,"tooltipTimeFormat":"smart_date","extra_form_data":{},"dashboards":[24],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: e6db36af-476b-45cf-88e0-3e88f7d05f64
version: 1.0.0
dataset_uuid: 6f0e873c-4069-47a3-9142-59597901384a
