slice_name: Caffe and Groceries
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  datasource: 57__table
  viz_type: echarts_timeseries_line
  x_axis: datetime
  time_grain_sqla: P1M
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: ammount
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 2276
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: REAL
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: SUM(ammount)
    optionName: metric_wj7er5l9kb_o13u8th1qz
  groupby:
  - category_fancy
  adhoc_filters:
  - expressionType: SIMPLE
    subject: datetime
    operator: TEMPORAL_RANGE
    comparator: No filter
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_cppoxgc0iw_b3pdrsk3bvm
  - expressionType: SIMPLE
    subject: ammount
    operator: <
    operatorId: LESS_THAN
    comparator: '0'
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_df3z41c4xgp_sixaoxmf3so
  - expressionType: SQL
    sqlExpression: "category NOT IN ('\u041F\u0435\u0440\u0435\u0432\u043E\u0434 \u043C\
      \u0435\u0436\u0434\u0443 \u0441\u0447\u0435\u0442\u0430\u043C\u0438', '\u041F\
      \u043E\u043F\u043E\u043B\u043D\u0435\u043D\u0438\u044F', '\u0410\u0432\u0438\
      \u0430\u0431\u0438\u043B\u0435\u0442\u044B', '12_trips', '\u0422\u0443\u0440\
      \u0430\u0433\u0435\u043D\u0442\u0441\u0442\u0432\u0430', 'transaction')"
    clause: WHERE
    subject: null
    operator: null
    comparator: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_9vrkr6iag0q_b2xwyhnpeil
  - expressionType: SQL
    sqlExpression: "description NOT IN ('\u041F\u0435\u0440\u0435\u0432\u043E\u0434\
      \ \u043C\u0435\u0436\u0434\u0443 \u0441\u0447\u0435\u0442\u0430\u043C\u0438\
      ')"
    clause: WHERE
    subject: null
    operator: null
    comparator: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_ol82incf6z9_no2q9ecq49
  - expressionType: SIMPLE
    subject: card_name
    operator: NOT IN
    operatorId: NOT_IN
    comparator:
    - "04_\u041E\u0442\u043F\u0443\u0441\u043A"
    - Black
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_m23bf3sdwlg_osov8b2d3l
  - expressionType: SIMPLE
    subject: category
    operator: IN
    operatorId: IN
    comparator:
    - 1_caffe
    - 2_groceries
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_27dlkwd4vdu_q34fjagbwmg
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  rolling_type: null
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  seriesType: line
  show_value: false
  stack: null
  markerSize: 6
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  rich_tooltip: true
  showTooltipTotal: true
  showTooltipPercentage: true
  tooltipTimeFormat: smart_date
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  extra_form_data: {}
  dashboards:
  - 24
query_context: "{\"datasource\":{\"id\":57,\"type\":\"table\"},\"force\":false,\"\
  queries\":[{\"filters\":[{\"col\":\"datetime\",\"op\":\"TEMPORAL_RANGE\",\"val\"\
  :\"No filter\"},{\"col\":\"ammount\",\"op\":\"<\",\"val\":\"0\"},{\"col\":\"card_name\"\
  ,\"op\":\"NOT IN\",\"val\":[\"04_\u041E\u0442\u043F\u0443\u0441\u043A\",\"Black\"\
  ]},{\"col\":\"category\",\"op\":\"IN\",\"val\":[\"1_caffe\",\"2_groceries\"]}],\"\
  extras\":{\"time_grain_sqla\":\"P1M\",\"having\":\"\",\"where\":\"(category NOT\
  \ IN ('\u041F\u0435\u0440\u0435\u0432\u043E\u0434 \u043C\u0435\u0436\u0434\u0443\
  \ \u0441\u0447\u0435\u0442\u0430\u043C\u0438', '\u041F\u043E\u043F\u043E\u043B\u043D\
  \u0435\u043D\u0438\u044F', '\u0410\u0432\u0438\u0430\u0431\u0438\u043B\u0435\u0442\
  \u044B', '12_trips', '\u0422\u0443\u0440\u0430\u0433\u0435\u043D\u0442\u0441\u0442\
  \u0432\u0430', 'transaction')) AND (description NOT IN ('\u041F\u0435\u0440\u0435\
  \u0432\u043E\u0434 \u043C\u0435\u0436\u0434\u0443 \u0441\u0447\u0435\u0442\u0430\
  \u043C\u0438'))\"},\"applied_time_extras\":{},\"columns\":[{\"timeGrain\":\"P1M\"\
  ,\"columnType\":\"BASE_AXIS\",\"sqlExpression\":\"datetime\",\"label\":\"datetime\"\
  ,\"expressionType\":\"SQL\"},\"category_fancy\"],\"metrics\":[{\"expressionType\"\
  :\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"certification_details\":null,\"\
  certified_by\":null,\"column_name\":\"ammount\",\"description\":null,\"expression\"\
  :null,\"filterable\":true,\"groupby\":true,\"id\":2276,\"is_certified\":false,\"\
  is_dttm\":false,\"python_date_format\":null,\"type\":\"REAL\",\"type_generic\":0,\"\
  verbose_name\":null,\"warning_markdown\":null},\"aggregate\":\"SUM\",\"sqlExpression\"\
  :null,\"datasourceWarning\":false,\"hasCustomLabel\":false,\"label\":\"SUM(ammount)\"\
  ,\"optionName\":\"metric_wj7er5l9kb_o13u8th1qz\"}],\"orderby\":[[{\"expressionType\"\
  :\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"certification_details\":null,\"\
  certified_by\":null,\"column_name\":\"ammount\",\"description\":null,\"expression\"\
  :null,\"filterable\":true,\"groupby\":true,\"id\":2276,\"is_certified\":false,\"\
  is_dttm\":false,\"python_date_format\":null,\"type\":\"REAL\",\"type_generic\":0,\"\
  verbose_name\":null,\"warning_markdown\":null},\"aggregate\":\"SUM\",\"sqlExpression\"\
  :null,\"datasourceWarning\":false,\"hasCustomLabel\":false,\"label\":\"SUM(ammount)\"\
  ,\"optionName\":\"metric_wj7er5l9kb_o13u8th1qz\"},false]],\"annotation_layers\"\
  :[],\"row_limit\":10000,\"series_columns\":[\"category_fancy\"],\"series_limit\"\
  :0,\"order_desc\":true,\"url_params\":{},\"custom_params\":{},\"custom_form_data\"\
  :{},\"time_offsets\":[],\"post_processing\":[{\"operation\":\"pivot\",\"options\"\
  :{\"index\":[\"datetime\"],\"columns\":[\"category_fancy\"],\"aggregates\":{\"SUM(ammount)\"\
  :{\"operator\":\"mean\"}},\"drop_missing_columns\":false}},{\"operation\":\"rename\"\
  ,\"options\":{\"columns\":{\"SUM(ammount)\":null},\"level\":0,\"inplace\":true}},{\"\
  operation\":\"flatten\"}]}],\"form_data\":{\"datasource\":\"57__table\",\"viz_type\"\
  :\"echarts_timeseries_line\",\"x_axis\":\"datetime\",\"time_grain_sqla\":\"P1M\"\
  ,\"x_axis_sort_asc\":true,\"x_axis_sort_series\":\"name\",\"x_axis_sort_series_ascending\"\
  :true,\"metrics\":[{\"expressionType\":\"SIMPLE\",\"column\":{\"advanced_data_type\"\
  :null,\"certification_details\":null,\"certified_by\":null,\"column_name\":\"ammount\"\
  ,\"description\":null,\"expression\":null,\"filterable\":true,\"groupby\":true,\"\
  id\":2276,\"is_certified\":false,\"is_dttm\":false,\"python_date_format\":null,\"\
  type\":\"REAL\",\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\":null},\"\
  aggregate\":\"SUM\",\"sqlExpression\":null,\"datasourceWarning\":false,\"hasCustomLabel\"\
  :false,\"label\":\"SUM(ammount)\",\"optionName\":\"metric_wj7er5l9kb_o13u8th1qz\"\
  }],\"groupby\":[\"category_fancy\"],\"adhoc_filters\":[{\"expressionType\":\"SIMPLE\"\
  ,\"subject\":\"datetime\",\"operator\":\"TEMPORAL_RANGE\",\"comparator\":\"No filter\"\
  ,\"clause\":\"WHERE\",\"sqlExpression\":null,\"isExtra\":false,\"isNew\":false,\"\
  datasourceWarning\":false,\"filterOptionName\":\"filter_cppoxgc0iw_b3pdrsk3bvm\"\
  },{\"expressionType\":\"SIMPLE\",\"subject\":\"ammount\",\"operator\":\"<\",\"operatorId\"\
  :\"LESS_THAN\",\"comparator\":\"0\",\"clause\":\"WHERE\",\"sqlExpression\":null,\"\
  isExtra\":false,\"isNew\":false,\"datasourceWarning\":false,\"filterOptionName\"\
  :\"filter_df3z41c4xgp_sixaoxmf3so\"},{\"expressionType\":\"SQL\",\"sqlExpression\"\
  :\"category NOT IN ('\u041F\u0435\u0440\u0435\u0432\u043E\u0434 \u043C\u0435\u0436\
  \u0434\u0443 \u0441\u0447\u0435\u0442\u0430\u043C\u0438', '\u041F\u043E\u043F\u043E\
  \u043B\u043D\u0435\u043D\u0438\u044F', '\u0410\u0432\u0438\u0430\u0431\u0438\u043B\
  \u0435\u0442\u044B', '12_trips', '\u0422\u0443\u0440\u0430\u0433\u0435\u043D\u0442\
  \u0441\u0442\u0432\u0430', 'transaction')\",\"clause\":\"WHERE\",\"subject\":null,\"\
  operator\":null,\"comparator\":null,\"isExtra\":false,\"isNew\":false,\"datasourceWarning\"\
  :false,\"filterOptionName\":\"filter_9vrkr6iag0q_b2xwyhnpeil\"},{\"expressionType\"\
  :\"SQL\",\"sqlExpression\":\"description NOT IN ('\u041F\u0435\u0440\u0435\u0432\
  \u043E\u0434 \u043C\u0435\u0436\u0434\u0443 \u0441\u0447\u0435\u0442\u0430\u043C\
  \u0438')\",\"clause\":\"WHERE\",\"subject\":null,\"operator\":null,\"comparator\"\
  :null,\"isExtra\":false,\"isNew\":false,\"datasourceWarning\":false,\"filterOptionName\"\
  :\"filter_ol82incf6z9_no2q9ecq49\"},{\"expressionType\":\"SIMPLE\",\"subject\":\"\
  card_name\",\"operator\":\"NOT IN\",\"operatorId\":\"NOT_IN\",\"comparator\":[\"\
  04_\u041E\u0442\u043F\u0443\u0441\u043A\",\"Black\"],\"clause\":\"WHERE\",\"sqlExpression\"\
  :null,\"isExtra\":false,\"isNew\":false,\"datasourceWarning\":false,\"filterOptionName\"\
  :\"filter_m23bf3sdwlg_osov8b2d3l\"},{\"expressionType\":\"SIMPLE\",\"subject\":\"\
  category\",\"operator\":\"IN\",\"operatorId\":\"IN\",\"comparator\":[\"1_caffe\"\
  ,\"2_groceries\"],\"clause\":\"WHERE\",\"sqlExpression\":null,\"isExtra\":false,\"\
  isNew\":false,\"datasourceWarning\":false,\"filterOptionName\":\"filter_27dlkwd4vdu_q34fjagbwmg\"\
  }],\"order_desc\":true,\"row_limit\":10000,\"truncate_metric\":true,\"show_empty_columns\"\
  :true,\"rolling_type\":null,\"comparison_type\":\"values\",\"annotation_layers\"\
  :[],\"forecastPeriods\":10,\"forecastInterval\":0.8,\"x_axis_title_margin\":15,\"\
  y_axis_title_margin\":15,\"y_axis_title_position\":\"Left\",\"sort_series_type\"\
  :\"sum\",\"color_scheme\":\"supersetColors\",\"seriesType\":\"line\",\"show_value\"\
  :false,\"stack\":null,\"markerSize\":6,\"show_legend\":true,\"legendType\":\"scroll\"\
  ,\"legendOrientation\":\"top\",\"x_axis_time_format\":\"smart_date\",\"rich_tooltip\"\
  :true,\"showTooltipTotal\":true,\"showTooltipPercentage\":true,\"tooltipTimeFormat\"\
  :\"smart_date\",\"y_axis_format\":\"SMART_NUMBER\",\"truncateXAxis\":true,\"y_axis_bounds\"\
  :[null,null],\"extra_form_data\":{},\"dashboards\":[24],\"force\":false,\"result_format\"\
  :\"json\",\"result_type\":\"full\"},\"result_format\":\"json\",\"result_type\":\"\
  full\"}"
cache_timeout: null
uuid: 717ddc5b-e3cc-4bb7-9aa4-cf592747168a
version: 1.0.0
dataset_uuid: 6f0e873c-4069-47a3-9142-59597901384a
