slice_name: Table
description: null
certified_by: null
certification_details: null
viz_type: pivot_table_v2
params:
  datasource: 57__table
  viz_type: pivot_table_v2
  slice_id: 260
  groupbyColumns:
  - datetime
  groupbyRows:
  - category_fancy
  time_grain_sqla: P1M
  temporal_columns_lookup:
    datetime: true
  metrics:
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: ammount
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 2276
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: REAL
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: SUM(ammount)
    optionName: metric_ly4er5r654_laa3vkw3kss
    sqlExpression: null
  metricsLayout: COLUMNS
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: datetime
  row_limit: 10000
  order_desc: true
  aggregateFunction: Sum
  rowTotals: true
  colTotals: true
  valueFormat: SMART_NUMBER
  date_format: smart_date
  rowOrder: key_a_to_z
  colOrder: key_a_to_z
  extra_form_data: {}
  dashboards:
  - 24
query_context: '{"datasource":{"id":57,"type":"table"},"force":false,"queries":[{"filters":[{"col":"datetime","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1M","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1M","columnType":"BASE_AXIS","sqlExpression":"datetime","label":"datetime","expressionType":"SQL"},"category_fancy"],"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"ammount","description":null,"expression":null,"filterable":true,"groupby":true,"id":2276,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"REAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(ammount)","optionName":"metric_ly4er5r654_laa3vkw3kss","sqlExpression":null}],"orderby":[[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"ammount","description":null,"expression":null,"filterable":true,"groupby":true,"id":2276,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"REAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(ammount)","optionName":"metric_ly4er5r654_laa3vkw3kss","sqlExpression":null},false]],"annotation_layers":[],"row_limit":10000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"57__table","viz_type":"pivot_table_v2","slice_id":260,"groupbyColumns":["datetime"],"groupbyRows":["category_fancy"],"time_grain_sqla":"P1M","temporal_columns_lookup":{"datetime":true},"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"ammount","description":null,"expression":null,"filterable":true,"groupby":true,"id":2276,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"REAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(ammount)","optionName":"metric_ly4er5r654_laa3vkw3kss","sqlExpression":null}],"metricsLayout":"COLUMNS","adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"datetime"}],"row_limit":10000,"order_desc":true,"aggregateFunction":"Sum","rowTotals":true,"colTotals":true,"valueFormat":"SMART_NUMBER","date_format":"smart_date","rowOrder":"key_a_to_z","colOrder":"key_a_to_z","extra_form_data":{},"dashboards":[24],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 712ec829-0c03-4711-b18d-faced186b85d
version: 1.0.0
dataset_uuid: 6f0e873c-4069-47a3-9142-59597901384a
